Update super-linter-docker.yml

diff --git a/.github/workflows/super-linter-docker.yml b/.github/workflows/super-linter-docker.yml
--- a/.github/workflows/super-linter-docker.yml
+++ b/.github/workflows/super-linter-docker.yml
@@ -28,6 +28,18 @@ jobs:
           VALIDATE_JSON: true
           VALIDATE_DOCKERFILE: true
 
+      # Test Docker Hub Login
+      - name: Test Docker Hub Login
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+        run: |
+          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+          if [ $? -eq 0 ]; then
+            echo "Docker Hub login successful"
+          else
+            echo "Docker Hub login failed"
+            exit 1
+          fi
+
       # Set up Docker Buildx
       - name: Set up Docker Buildx
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
@@ -38,8 +50,8 @@ jobs:
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: docker/login-action@v3
         with:
-          username: ${{DOCKERHUB_USERNAME}}
-          password: ${{DOCKERHUB_TOKEN}}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       # Build and push Docker image
       - name: Build and push Docker image
@@ -50,7 +62,7 @@ jobs:
           file: ./Dockerfile
           push: true
           tags: |
-            ${balemus1}/my-app:${{ github.sha }}
-            ${balemus1}/my-app:latest
+            ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
+            ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
           cache-from: type=gha
           cache-to: type=gha,mode=max
